name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: actions/cache@v4
        with:
          path: .build
          key: ${{ runner.os }}-Markup-${{ hashFiles('**/Package.resolved', '**/.gitmodules') }}
          restore-keys: ${{ runner.os }}-Markup
      - name: Build
        run: swift build
      - name: Test
        run: swift test
